### ISSUE TITLE
Bids below zero

### ISSUE THREAD

**Issue by jordi2105** [meesf/RiskyGamesAndAgents#120]
We should fix it that it will be less frequent that a bid has a utility below zero. So, the parameters that give a negative bonus, CV ENEMY NEIGHBOR (-0.3) for example, is perhaps to strong. We might change this to -0.1 for example. So that the value of a country will be a bit higher.

**Comment by Uwila** [comment]
There was the problem that the weight for enemy territory was used instead of the weight for enemy units, when multiplying with enemy units, creating a tenfold effect. It's hopefully fixed now.
