### ISSUE TITLE
Leave more than one unit when invading

### ISSUE THREAD

**Issue by jordi2105** [meesf/RiskyGamesAndAgents#135]
Now, when you invade a country you will leave 1 unit behind. We should add some smartness here. In many cases, it is convenient to leave perhaps more units behind. Think about this.

**Comment by Waxmeneer** [comment]
If you plan your path well this is almost never needed. The only territories needing more than 1 army are territories bordering enemies worth stuff (e.g: chokepoints, continent borders). Just reinforcing (at the end of turn) should be enough imho.
