### ISSUE TITLE
Sometimes only 0 units remain

### ISSUE THREAD

**Issue by Uwila** [meesf/RiskyGamesAndAgents#144]
This could mean a bug in attacking, taking a territory, or giving units away with fortification.

**Comment by jordi2105** [comment]
At 11:00 11/06/18 this was a problem while using the random seed: 1. It happened somewhere between rounds 234 and 239. However, Around this time a new pull request was merged which looks likes it fixes this problem.

**Comment by Uwila** [comment]
At commit `fa3fe9f2e2b1ff18df90bf336e6eb5bf679370d5` which exists in branch `better-utilities` with seed 1528727576498 this bug will trigger. You will do this @jordi2105 ?

**Comment by Uwila** [comment]
I think I actually happened to come across the malfunctioning code, will post a fix soon
