### ISSUE TITLE
Save/Load the state of the game

### ISSUE THREAD

**Issue by meesf** [meesf/RiskyGamesAndAgents#161]
This is useful to see how the behaviour of the agent changes when we tweak the parameters.

**Comment by Uwila** [comment]
Would it not be more useful to just create some helper methods to create a certain gamestate? We also already have the possibility to fix the random seed

**Comment by meesf** [comment]
Doesn't it in the end come down to the same method? 
What do you mean with the latter part? I think the seed of the random function should not be remembered neccesarily, because that only effects the outcome of his actions, not his thought process. Which is exactly what should be happening right?

**Comment by meesf** [comment]
I think we agreed to use a seed instead of loading the game state. So this issue will be closed.
