### ISSUE TITLE
Bonus for eliminating a player

### ISSUE THREAD

**Issue by jordi2105** [meesf/RiskyGamesAndAgents#166]
Eliminating a player gives you the cards of the player you have killed, so doing this should give you a bonus. This should be done on goal-level, since it could be the case that you need to attack 3 countries to defeat a player.

**Comment by Uwila** [comment]
This is already in the game

**Comment by Uwila** [comment]
https://github.com/meesf/RiskyGamesAndAgents/pull/159/commits/73890aa2c4ac2778c73dd31b8960386f18b37c4b
