### ISSUE TITLE
Check the rules and see what (and if) we are doing stuff differently

### ISSUE THREAD

**Issue by jordi2105** [meesf/RiskyGamesAndAgents#169]
So we can add this to the report. Link:  https://www.fgbradleys.com/rules//Risk.pdf

**Comment by Mljinki** [comment]
for now 2 deviation from the rules
1. We dont exchange the cards when we have a combination before having 5 of them

2. We use the same initial starting number of the armies in the beginning regardless of how many players start the game

**Comment by Uwila** [comment]
The first I don't think is a deviation from the rules: What we do is allowed within the official rules, we just don't do everything that is allowed. And it's actually one thing we should probably still add, but even without adding it we are still following the rules.

**Comment by Uwila** [comment]
The second is also something we could easily fix so let's do that instead

**Comment by Uwila** [comment]
Actually now that I think about it we probably shouldn't be adding it to the report but instead we should fix it in the program, if we break the official rules anywhere.

**Comment by Mljinki** [comment]
3. our cards dont have country labels on them right? The rule is if you draw a card with the country on it that you own, that country gets 2 troops on it when the cards are turned in
