### ISSUE TITLE
Find interesting events in the simulations 

### ISSUE THREAD

**Issue by jordi2105** [meesf/RiskyGamesAndAgents#194]
For the presentation, it might be nice to show some games which have interesting things happening. For example:
- Some nice fortification (that he places armies on chokepoints for example)
- Show that the agent tries to take over a continent

Of course with the different types of agents. It would be nice if the events happen earlier in the game, since we do have to set the speed very low to see stuff happening.

I think it would not even be that bad to show some weak points of our program.

**Comment by Uwila** [comment]
are we 100% sure that we won't change any behavior at all? If not then any seeds would be useless

**Comment by jordi2105** [comment]
True, we should do this when we are sure
