### ISSUE TITLE
Information box

### ISSUE THREAD

**Issue by meesf** [meesf/RiskyGamesAndAgents#29]
Add a information box on the right side of the board that presents 
- the current player
- players that are defeated
- the position of the golden cavalry
- the number of cards that each player has and what types of cards (maybe this should differ if only AI's are playing, or when a human is playing)
- a log of the actions taken.
- (maybe also the number of reinforcements/units/countries)

**Comment by Uwila** [comment]
This is partially done, but not fully. Look at RiskVisual.updateGameInfo
