### ISSUE TITLE
MARS

### ISSUE THREAD

**Issue by jordi2105** [meesf/RiskyGamesAndAgents#52]
Implement the MARS in https://www.diva-portal.org/smash/get/diva2:831092/FULLTEXT01.pdf. Create TerritoryAgents which are used by the bot. Therefore you need to extend the player class and create a new bot (for inspiration: look at the bot class). The parameters used in the TerritoryAgents should be in the bot.

**Comment by Uwila** [comment]
Please build on the mars branch. It would be optimal to work in other branches, merge the progress into mars continually, and merge that into master when it's usable.

**Comment by jordi2105** [comment]
Jongens ik wens jullie veel plezier met deze supergave opdracht
