### ISSUE TITLE
Add new parameters to MARS

### ISSUE THREAD

**Issue by meesf** [meesf/RiskyGamesAndAgents#81]
Come up with new parameters that can be tweaked. Add them to MARS. 
Example parameters:
- History with opponents --> Forgiving/Vengeful player
- Preferences for certain countries/continents
- Preferences for players, (almost) never attack one opponent
- more..

**Comment by Waxmeneer** [comment]
Imma do this

**Comment by Waxmeneer** [comment]
Use the log Lars is making

**Comment by jordi2105** [comment]
How is this going?
