### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by meesf** [meesf/RiskyGamesAndAgents#85]
Start working on the report. Report latex project: https://www.overleaf.com/16551800rfqrhfjmqwtn
This should include: 
- Introduction --> problem description, motivation, novelty
- Literature --> Literature we used, also the literature we did not use with explanation why we did not use it.
- Description of AI technique used. Give all necessary equations or rules to implement a chosen algorithm
- Description of environment, states, actions, goals.
- Experiments
- Results
- Conclusion
- Appendix --> Containing log of contribution of each member (every member needs some contribution to literature and programming), a step by step guide how we implemented the Risk game in Java.
- References

**Comment by jordi2105** [comment]
I'm starting on this
