### ISSUE TITLE
Check if defensive bid is working

### ISSUE THREAD

**Issue by meesf** [meesf/RiskyGamesAndAgents#92]
Jordi and i speculated about the defendive bid algorithm. Lets assume we are in th reinforcement phase and there are two territories A and B. Both are surrounded by two enemy territories with 5 enemy units each. The teritory values of A and B are the same, but A has 1 unit and B has 20 units. MARS has 5 reinforcements in total. Will MARS reinforce A or will he reinforce B (if the offensive bids are disregarded)? For both decisions is something to say.

**Comment by Uwila** [comment]
Is this not duplicate of #91 ?
